package games

var GAME_WIDTH = 200
var GAME_HEIGHT = 200

var PLAYER_WIDTH = 25
var PLAYER_HEIGHT = 3
var PLAYER_MOVEMENT_SCALE_FACTOR = 5
var PLAYER_VELOCITY_INCREMENT = 0.1
var MAX_PLAYER_VELOCITY = PLAYER_VELOCITY_INCREMENT * 3

var DEFAULT_BALL_RADIUS = 2

var FRAME_TIME = 17
