package games

var ACTIVATE_PLAYER = "ACTIVATE_PLAYER"
var CLEAN_UP_CONNECTION = "CLEAN_UP_CONNECTION"
var START_STATUS_UPDATES = "START_STATUS_UPDATES"
var STOP_LISTENING = "STOP_LISTENING"
var REGISTER_PLAYER_MOVEMENT = "REGISTER_PLAYER_MOVEMENT"

var MOVEMENT_SCALE_FACTOR = 3
